// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKm3D0Bp2-6wdcJuyIvyWBo1DznL-Oj9s',
    appId: '1:964972179458:web:a5154579d6e8c010abf71b',
    messagingSenderId: '964972179458',
    projectId: 'campuseat-c4318',
    authDomain: 'campuseat-c4318.firebaseapp.com',
    storageBucket: 'campuseat-c4318.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM68xF14rDVWmc_S1qzbwU_JjhvgTqHXs',
    appId: '1:964972179458:android:b278d51863a957e4abf71b',
    messagingSenderId: '964972179458',
    projectId: 'campuseat-c4318',
    storageBucket: 'campuseat-c4318.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnFgaEWPX0_X9PKhPd9YXPcor7NX844ZI',
    appId: '1:964972179458:ios:410c16119b9d4ce9abf71b',
    messagingSenderId: '964972179458',
    projectId: 'campuseat-c4318',
    storageBucket: 'campuseat-c4318.firebasestorage.app',
    iosClientId: '964972179458-4thnbnq7j4udthrokhv1gn07a8hjbe8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusEat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnFgaEWPX0_X9PKhPd9YXPcor7NX844ZI',
    appId: '1:964972179458:ios:410c16119b9d4ce9abf71b',
    messagingSenderId: '964972179458',
    projectId: 'campuseat-c4318',
    storageBucket: 'campuseat-c4318.firebasestorage.app',
    iosClientId: '964972179458-4thnbnq7j4udthrokhv1gn07a8hjbe8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusEat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKm3D0Bp2-6wdcJuyIvyWBo1DznL-Oj9s',
    appId: '1:964972179458:web:dc894875d614f4f3abf71b',
    messagingSenderId: '964972179458',
    projectId: 'campuseat-c4318',
    authDomain: 'campuseat-c4318.firebaseapp.com',
    storageBucket: 'campuseat-c4318.firebasestorage.app',
  );
}
