// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsWHA8827s9TY42Fg2yGQwOeymSk7Q3Jw',
    appId: '1:254986384951:web:1a6ccd2ff54a832496b1b2',
    messagingSenderId: '254986384951',
    projectId: 'appconn-fe65d',
    authDomain: 'appconn-fe65d.firebaseapp.com',
    databaseURL: 'https://appconn-fe65d-default-rtdb.firebaseio.com',
    storageBucket: 'appconn-fe65d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4rsLteRjGq3ShBAwXMHg1T9rTPUnEMIA',
    appId: '1:254986384951:android:5ab8e10d61809c2a96b1b2',
    messagingSenderId: '254986384951',
    projectId: 'appconn-fe65d',
    databaseURL: 'https://appconn-fe65d-default-rtdb.firebaseio.com',
    storageBucket: 'appconn-fe65d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsZXg253wTXwC5GSJj5eJCuQT1Auy1_yY',
    appId: '1:254986384951:ios:5bf23e4c5356fedb96b1b2',
    messagingSenderId: '254986384951',
    projectId: 'appconn-fe65d',
    databaseURL: 'https://appconn-fe65d-default-rtdb.firebaseio.com',
    storageBucket: 'appconn-fe65d.firebasestorage.app',
    iosClientId: '254986384951-6vv8q9qss99b5fmcmb8si84n44hhvvdl.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusEat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsZXg253wTXwC5GSJj5eJCuQT1Auy1_yY',
    appId: '1:254986384951:ios:5bf23e4c5356fedb96b1b2',
    messagingSenderId: '254986384951',
    projectId: 'appconn-fe65d',
    databaseURL: 'https://appconn-fe65d-default-rtdb.firebaseio.com',
    storageBucket: 'appconn-fe65d.firebasestorage.app',
    iosClientId: '254986384951-6vv8q9qss99b5fmcmb8si84n44hhvvdl.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusEat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsWHA8827s9TY42Fg2yGQwOeymSk7Q3Jw',
    appId: '1:254986384951:web:ba7cb61a2bf8159196b1b2',
    messagingSenderId: '254986384951',
    projectId: 'appconn-fe65d',
    authDomain: 'appconn-fe65d.firebaseapp.com',
    databaseURL: 'https://appconn-fe65d-default-rtdb.firebaseio.com',
    storageBucket: 'appconn-fe65d.firebasestorage.app',
  );

}